{% set name = "Orange3-Associate" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 877ca1dc81a892cb98898598ea7becbf9b780ebc2f0800a54e376fcb2f4acca1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - Orange3 >=3.25.0

test:
  imports:
    - orangecontrib.associate

about:
  home: http://orange.biolab.si/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Frequent itemsets and association rules mining for Orange 3'
  description: |
    Orange add-on for enumerating frequent itemsets and association rules mining
  doc_url: https://orange3-associate.readthedocs.io/
  dev_url: https://github.com/biolab/orange3-associate

extra:
  recipe-maintainers:
    - primozgodec
    - markotoplak
    - ajdapretnar
    - JakaKokosar
